const Groq = require("groq-sdk");

const groq = new Groq({
    apiKey: process.env.GROQ_API_KEY
});

const interviewReportSchemaString = `
{
    "matchScore": "number between 0 and 100",
    "technicalQuestions": [
        {
            "question": "string",
            "intention": "string",
            "answer": "string"
        }
    ],
    "behavioralQuestions": [
        {
            "question": "string",
            "intention": "string",
            "answer": "string"
        }
    ],
    "skillGaps": [
        {
            "skill": "string",
            "severity": "low | medium | high"
        }
    ],
    "preparationPlan": [
        {
            "day": 1,
            "focus": "string",
            "tasks": ["string", "string"]
        }
    ],
    "title": "Job Title"
}
`;

async function generateInterviewReport({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate an interview report for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

You MUST return a pure JSON object that strictly follows this exact JSON structure and keys:
${interviewReportSchemaString}`;

    try {
        const response = await groq.chat.completions.create({
            model: "qwen/qwen3.8-27b",
            messages: [
                { role: "system", content: "You are a pure JSON generation machine. You MUST return ONLY valid JSON. No conversational text. No markdown blocks." },
                { role: "user", content: prompt }
            ],
            temperature: 0.2
        });

        let rawText = response.choices[0].message.content;
        console.log("Raw AI output:", rawText);

        rawText = rawText.replace(/```json/g, "").replace(/```/g, "").trim();
        const jsonMatch = rawText.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
            rawText = jsonMatch[0];
        }

        return JSON.parse(rawText);
    } catch (err) {
        console.error("❌ Groq API Error:", err);
        throw err;
    }
}

async function generateResumePdf({ resume, selfDescription, jobDescription }) {
    const prompt = `Generate resume for a candidate with the following details:
Resume: ${resume}
Self Description: ${selfDescription}
Job Description: ${jobDescription}

the response should be a JSON object with a single field "html" which contains the HTML content of the resume.
The resume should be tailored for the given job description and should highlight the candidate's strengths and relevant experience. The HTML content should be well-formatted and structured, making it easy to read and visually appealing.
The content of resume should be not sound like it's generated by AI and should be as close as possible to a real human-written resume.
you can highlight the content using some colors or different font styles but the overall design should be simple and professional.
The content should be ATS friendly, i.e. it should be easily parsable by ATS systems without losing important information.

You MUST return a pure JSON object exactly like this: { "html": "<your html here>" }`;

    try {
        const response = await groq.chat.completions.create({
            model: "qwen/qwen3.8-27b",
            messages: [
                { role: "system", content: "You are a pure JSON generation machine. You MUST return ONLY valid JSON. No conversational text. No markdown blocks." },
                { role: "user", content: prompt }
            ],
            temperature: 0.2
        });

        let rawText = response.choices[0].message.content;
        console.log("Raw Resume Output:", rawText);

        // Remove markdown formatting if the model still added it
        rawText = rawText.replace(/```json/g, "").replace(/```html/g, "").replace(/```/g, "").trim();

        // Attempt to extract json object if there's conversational text
        const jsonMatch = rawText.match(/\{[\s\S]*\}/);
        if (jsonMatch) {
            rawText = jsonMatch[0];
        }

        const jsonContent = JSON.parse(rawText);
        return jsonContent.html;
    } catch (err) {
        console.error("❌ Groq API Error:", err);
        throw err;
    }
}

module.exports = { generateInterviewReport, generateResumePdf };